name = "secret"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Serve the HTML files from the 'public' folder
[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "secret"
database_id = "2e8b8482-f6bd-43ee-bdf9-7394a23cd76e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "secret"
